version: '3.9'
services:
  assignment-admin-service:
    container_name: ${CONTAINER_NAME}
    image: registry.assignment.xyz/${CONTAINER_NAME}
    restart: unless-stopped
    tty: true
    env_file: ../../.env
    networks:
        - assignment-admin-service-network
    healthcheck:
      test: curl -sS http://127.0.0.1/health-check || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
